name: 'Flutter Package Updater'
author: 'Tianhao Zhou'
description: 'Flutter package update automation'
inputs:
  git-email:
    description: 'The email pull request should be associated with'
    required: false
    default: 'example@flutterbot.com'
  git-name:
    description: 'The name pull request should be associated with'
    required: false
    default: 'flutter bot'
  target-branch:
    description: 'The main branch of the repository where pull requests should be sent to.'
    required: false
    default: 'master'
  temp-branch:
    description: 'The branch to get created to update the packages.'
    required: false
    default: 'chore/update-flutter-packages'
  title:
    description: 'The title of the pull request'
    required: false
    default: '[flutter package updater] Automated Flutter Packages Update'
  token:
    description: 'GitHub token used to open pull requests'
    required: false
    default: 'local'
  log:
    description: 'The logging level which can be quiet, info, warning or error.'
    required: false
    default: 'quiet'
  flutter-project:
    description: 'The root directory of the Flutter project of interest.'
    required: false
    default: './'
runs:
  using: 'node12'
  main: 'lib/index.js'
branding:
  icon: 'activity'  
  color: 'green'