on: [push]

jobs:
  test-drive:
    runs-on: ubuntu-latest
    name: test flutter package update
    steps:
      - name: checkout source
        uses: actions/checkout@v2
      - name: run flutter package updater
        uses: ./
        with:
          flutter-project: './lab-rat'
